import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header.jsx'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer.jsx'
import Products from '../components/products.jsx'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Products />
      <Footer />
    </div>
  )
}
